output-folder: SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights
customFunctionPrefix: JcSdk
clear-output-folder: true
module-name: JumpCloud.SDK.DirectoryInsights
prefix: JcSdkInternal
branch: CUT-4981_v2EUSupport
input-file:
- SwaggerSpecs/JumpCloud.SDK.DirectoryInsights.json
sample-generation: true
powershell: true
dll-name: JumpCloud.SDK.DirectoryInsights.private
base-folder: ..
debug: true
module-version: 0.1.1
metadata:
  iconUri: https://console.jumpcloud.com/img/login-viewport-logo.png
  licenseUri: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/LICENSE
  description: The JumpCloud DirectoryInsights PowerShell SDK
  owners: JumpCloud
  companyName: JumpCloud
  formatsToProcess: []
  copyright: (c) JumpCloud. All rights reserved.
  tags: JumpCloud, DaaS, Jump, Cloud, Directory
  requireLicenseAcceptance: false
  authors: JumpCloud
  projectUri: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights/
namespace: JumpCloud.SDK.DirectoryInsights
help-link-prefix: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/SDKs/PowerShell/
directive:
- where:
    prefix: JcSdk
  hide: true
verbose: true
