sample-generation: true
directive:
- hide: true
  where:
    prefix: JcSdk
input-file:
- SwaggerSpecs/JumpCloud.SDK.DirectoryInsights.json
module-version: 0.1.0
output-folder: SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights
clear-output-folder: true
base-folder: ..
branch: CUT-4908_userGroupDeviceGroupFilters
dll-name: JumpCloud.SDK.DirectoryInsights.private
namespace: JumpCloud.SDK.DirectoryInsights
help-link-prefix: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/SDKs/PowerShell/
verbose: true
debug: true
metadata:
  requireLicenseAcceptance: false
  companyName: JumpCloud
  tags: JumpCloud, DaaS, Jump, Cloud, Directory
  copyright: (c) JumpCloud. All rights reserved.
  iconUri: https://console.jumpcloud.com/img/login-viewport-logo.png
  licenseUri: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/LICENSE
  description: The JumpCloud DirectoryInsights PowerShell SDK
  projectUri: https://github.com/TheJumpCloud/jcapi-powershell/tree/$(branch)/SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights/
  owners: JumpCloud
  formatsToProcess: []
  authors: JumpCloud
module-name: JumpCloud.SDK.DirectoryInsights
prefix: JcSdkInternal
customFunctionPrefix: JcSdk
powershell: true
